<a href="https://colab.research.google.com/github/zacherymoy/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/Zachery_Moy_DS_431_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img align="left" src="https://lever-client-logos.s3.amazonaws.com/864372b1-534c-480e-acd5-9711f850815c-1524247202159.png" width=200>
<br></br>
<br></br>

# Neural Networks

## *Data Science Unit 4 Sprint 2 Assignment 1*

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: Artificial neural networks are typically composed of input layers, hidden layers and output layers. The input layer is the very beginning of the workflow for the artificial neural network.


### Hidden Layer: Artificial neural networks are typically composed of input layers, hidden layers and output layers. A hidden layer in an artificial neural network is a layer in between input layers and output layers, where artificial neurons take in a set of weighted inputs and produce an output through an activation function. It is a typical part of nearly any neural network in which engineers simulate the types of activity that go on in the human brain.


### Output Layer: Artificial neural networks are typically composed of input layers, hidden layers and output layers. The output layer in an artificial neural network is the last layer of neurons that produces given outputs for the program.


### Neuron: In this context, artificial neurons are similar to human nuerons. Programmers are inputting data for the computer to analyze. 


### Weight: Weights of a feature denote how much the feature matters in the model. This is a variable that can be used to better train your model. 


### Activation Function: Defines the output of that node given an input or set of inputs


### Node Map: How nodes are then organized into layers to comprise a network.


### Perceptron: The perceptron is an algorithm for supervised learning of binary classifiers.


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

A neural network is just a linear function with a non-linearity at the end, repeated over and over again.

When you first input weights and biases will affect the inputs as you are training the model. These inputs are going through multiple layers such as through activation functions. The activation function is a mathematical “gate” in between the input feeding the current neuron and its output going to the next layer.

At the end of the workflow is your output. 

## Write your own perceptron code that can correctly classify (99.0% accuracy) a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import pandas as pd
import numpy as np

data = { 'x1': [0,1,0,1],
         'x2': [0,0,1,1],
         'y':  [1,1,1,0]
       }

df = pd.DataFrame.from_dict(data).astype('int')

In [0]:
weights = np.random.random((2,1))
weights

array([[0.35090441],
       [0.37065389]])

In [0]:
dfnp = df.to_numpy()
dfnp

array([[0, 0, 1],
       [1, 0, 1],
       [0, 1, 1],
       [1, 1, 0]])

In [0]:
inputs = dfnp[:, 0:2]
inputs

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1]])

In [0]:
correct_outputs = dfnp[:, 2]
correct_outputs = [[1],[1],[1],[0]]

In [0]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    sx = sigmoid(x)
    return sx * (1-sx)

In [0]:
# inputs = np.array([
                  # [0,0,1],
                  # [1,1,1],
                  # [1,0,1],
                  # [0,1,1]                   
# 
# ])
# 
# 
# correct_outputs = [[0], [1], [1], [0]]

#is input the same as data? 

weights = 2 * np.random.random((4,2)) -1


In [0]:
inputs.shape, weights.shape

((4, 2), (2, 1))

In [0]:
weighted_sum = np.dot(inputs, weights)
weighted_sum

array([[0.        ],
       [0.35090441],
       [0.37065389],
       [0.7215583 ]])

In [0]:
# activated value 
activated_output = sigmoid(weighted_sum)
activated_output

array([[0.5       ],
       [0.58683688],
       [0.59161697],
       [0.67295007]])

In [0]:
# Cac error
error = correct_outputs - activated_output
    
adjustments = error * sigmoid_derivative(weighted_sum)

In [0]:
weights += np.dot(inputs.T, adjustments)
weights

array([[0.30297126],
       [0.3212134 ]])

In [0]:
print("Weights after training")
print(weights)

Weights after training
[[0.30297126]
 [0.3212134 ]]


In [0]:
print("Output after training")
print(activated_output)

Output after training
[[0.5       ]
 [0.58683688]
 [0.59161697]
 [0.67295007]]


In [0]:
# Left off the expected values. 

In [0]:
def calculate(inputs, weights, correct_ouputs):
    
    for iteration in range(10000):

        # Weighted sum of inputs / weights
        weighted_sum = np.dot(inputs, weights)
        
        activated_output = 1 / (1 + np.exp(-weighted_sum))

        # Cac error
        error = correct_outputs - activated_output
        
        sigmoid_derivative = activated_output * (1-activated_output)

        adjustments = error * sigmoid_derivative

        # Update the Weights
        weights += np.dot(inputs.T, adjustments)

    print("Weights after training")
    print(weights)

    print("Output after training")
    print(activated_output)

In [0]:
calculate(inputs, weights, correct_outputs)


Weights after training
[[-3.19189120e-16]
 [ 1.52655666e-16]]
Output after training
[[0.5]
 [0.5]
 [0.5]
 [0.5]]


## Implement your own Perceptron Class and use it to classify a binary dataset: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [0]:
diabetes = pd.read_csv('https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv')
diabetes.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]
n = Normalizer()

X = diabetes[feats]
Xn = n.fit_transform(X)
y = np.array([[r] for r in diabetes['Outcome']])
print(Xn[:5])
y[:5]

[[0.03355237 0.82762513 0.40262844 0.19572216 0.         0.18789327
  0.00350622 0.27960308]
 [0.008424   0.71604034 0.55598426 0.24429612 0.         0.22407851
  0.00295683 0.26114412]
 [0.04039768 0.92409698 0.32318146 0.         0.         0.11765825
  0.00339341 0.16159073]
 [0.00661199 0.58846737 0.43639153 0.15207584 0.62152733 0.185797
  0.0011042  0.13885185]
 [0.         0.5963863  0.17412739 0.15236146 0.73133502 0.18762226
  0.00996009 0.14365509]]


array([[1],
       [0],
       [1],
       [0],
       [1]])

In [0]:
class Perceptron:
    
    def __init__(self, rate = 0.01, niter = 10):
        self.rate = rate
        self.niter = niter
    
    def __sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def __sigmoid_derivative(self, x):
        sx = sigmoid(x)
        return sx * (1-sx)
    
    def fit(self, X, y):
        """Fit training data
        X : Training vectors, X.shape : [#samples, #features]
        y : Target values, y.shape : [#samples]
        """

        # Randomly Initialize Weights
        self.weight = np.zeros(1 + X.shape[1])
        self.errors = []
        
        for i in range(self.niter):
          err = 0
          for xi, target in zip(X, y):
            delta_w = self.rate * (target - self.predict(xi))
            self.weight[1:] += delta_w * xi
            self.weight[0] += delta_w
            err += int(delta_w != 0.0)
          self.errors.append(err)
        return self

    def net_input(self, X):
        """Calculate net input"""
        return np.dot(X, self.weight[1:]) + self.weight[0]

    def predict(self, X):
        """Return class label after unit step"""
        """ Default Step Function"""
        return np.where(self.net_input(X) >= 0.0, 1, -1)

p = Perceptron()
p.fit(Xn, y)
print(p.predict(Xn)[:10])
print(y[:10])

[1 1 1 1 1 1 1 1 1 1]
[[1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]]


## What I've tried

In [0]:
#this = Perceptron()


In [0]:
#this.fit(X,y)

In [0]:
# Code in class 

# y = df.iloc[0:100, 4].values
# y

In [0]:
# Code in class 

# y = np.where(y == 'Iris-setosa', -1, 1)
# y

Although neural networks can handle non-normalized data, scaling or normalizing your data will improve your neural network's learning speed. Try to apply the sklearn `MinMaxScaler` or `Normalizer` to your diabetes dataset. 

In [0]:
from sklearn.preprocessing import MinMaxScaler, Normalizer

feats = list(diabetes)[:-1]

X = ...

In [0]:
##### Update this Class #####

class Perceptron:
    
    def __init__(self, niter = 10):
        self.niter = niter
    
    def __sigmoid(self, x):
        return None
    
    def __sigmoid_derivative(self, x):
        return None

    def fit(self, X, y):
    """Fit training data
    X : Training vectors, X.shape : [#samples, #features]
    y : Target values, y.shape : [#samples]
    """

        # Randomly Initialize Weights
        weights = ...

        for i in range(self.niter):
            # Weighted sum of inputs / weights

            # Activate!

            # Cac error

            # Update the Weights


    def predict(self, X):
    """Return class label after unit step"""
        return None

In [0]:
# Code in class 

# class Perceptron(object):
    
#     def __init__(self, rate = 0.01, niter = 10):
#         self.rate = rate
#         self.niter = niter
        
#     def fit(self, X, y):
#         """Fit training data
#         X : Training vectors, X.shape : [#samples, #features]
#         y : Target values, y.shape : [#samples]
#         """

#         # weights
#         self.weight = np.zeros(1 + X.shape[1])

#         # Number of misclassifications
#         self.errors = []  # Number of misclassifications

#         for i in range(self.niter):
#           err = 0
#           for xi, target in zip(X, y):
#             delta_w = self.rate * (target - self.predict(xi))
#             self.weight[1:] += delta_w * xi
#             self.weight[0] += delta_w
#             err += int(delta_w != 0.0)
#           self.errors.append(err)
#         return self

#     def net_input(self, X):
#         """Calculate net input"""
#         return np.dot(X, self.weight[1:]) + self.weight[0]

#     def predict(self, X):
#         """Return class label after unit step"""
#         """ Default Step Function"""
#         return np.where(self.net_input(X) >= 0.0, 1, -1)

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?

You backpropagate gradients by calculating partial derivatives with respect to each of our parameters and inputs. To do this, you use the chain rule.

There's different types of activation functions and this reminds me of how people do pros and cons for algorithms. For example there's Rectified Linear Activation Function and Sigmoid activation functions. In general, your neural network will have two types of activation functions. The first will be the activation function used in hidden layers and the second will be used in the output layer. 